### ISSUE TITLE
No module named 'dynamicprompts'

### ISSUE THREAD

**Issue by gobshyte** [adieyal/comfyui-dynamicprompts#24]
Hi

Any idea why I am getting this please?

Traceback (most recent call last):
  File "C:\SDAI\ComfyUI\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts\nodes\__init__.py", line 1, in <module>
    from .combinatorial import DPCombinatorialGenerator
  File "C:\SDAI\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts\nodes\combinatorial.py", line 3, in <module>
    from dynamicprompts.enums import SamplingMethod
ModuleNotFoundError: No module named 'dynamicprompts'

Cannot import C:\SDAI\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts module for custom nodes: No module named 'dynamicprompts'

**Comment by gobshyte** [comment]
My bad sorry, I was using the wrong python install, I used the embedded python under comfyui folder and it's now working.
