### ISSUE TITLE
Can't load Dynamic Prompts

### ISSUE THREAD

**Issue by Xenodimensional** [adieyal/comfyui-dynamicprompts#41]
This is what it throws at me, I tried removing and re-installing and updating the ui

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1282, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\pipelines\__init__.py", line 28, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tensorflow\__init__.py", line 45, in <module>
    from tensorflow.python import tf2 as _tf2
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\tensorflow\python\tf2.py", line 21, in <module>
    from tensorflow.python.platform import _pywrap_tf2
ImportError: DLL load failed while importing _pywrap_tf2: A dynamic link library (DLL) initialization routine failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts\nodes\__init__.py", line 4, in <module>
    from .magicprompt import DPMagicPrompt
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts\nodes\magicprompt.py", line 4, in <module>
    from dynamicprompts.generators.magicprompt import MagicPromptGenerator
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\dynamicprompts\generators\magicprompt.py", line 13, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
DLL load failed while importing _pywrap_tf2: A dynamic link library (DLL) initialization routine failed.

Cannot import C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts module for custom nodes: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
DLL load failed while importing _pywrap_tf2: A dynamic link library (DLL) initialization routine failed.

**Comment by Xenodimensional** [comment]
Issue still present. I have switched to the Wildcard prompts nodes and live in hope it's just a temporary thing :)

**Comment by Xenodimensional** [comment]
The issue is still present, I tried uninstalling TF - I ran the following command in CMD in the Comfy python embed folder, the site packages folder, in the main comfy folder etc:

$ pip uninstall tensorflow
WARNING: Skipping tensorflow as it is not installed.

I used the **install pip packages** feature of the Comfy Manager and it says: Requirement already satisfied: tensorflow in c:\comfyui_windows_portable\python_embeded\lib\site-packages (2.15.0) (Plus a lot more)

I would really appreciate if someone could help me and break it down - Can I delete all the tensorflow folders in the site packages folder and try reinstalling from the manager and hope for the best?

**Comment by Xenodimensional** [comment]
Thanks for the help /s

**Comment by Xenodimensional** [comment]
Anyone? I still can't get this to work? Please help!!

**Comment by Xenodimensional** [comment]
At this point I have to consider this extension to be abandonware?

**Comment by HydraBucket** [comment]
Im having the same error

**Comment by Xenodimensional** [comment]
I'm sorry to hear, the developer has been mia for months and I haven't been able to fix it :(

**Comment by Xenodimensional** [comment]
Wow, thanks for your help Mr developer /s. Six months since I placed this request for help and you have dropped this like a proverbial bag of flaming crap it seems. Cheers.

**Comment by sfinktah** [comment]
So. The solution is to remove the "Magic Prompt" capability.  You'll have to edit `custom_nodes/comfyui-dynamicprompts/nodes/__init__.py` and remove the three lines containing the word `magic`.  The result should be:

```
from .combinatorial import DPCombinatorialGenerator
from .feeling_lucky import DPFeelingLucky
from .jinja import DPJinja
from .output_node import OutputString
from .random import DPRandomGenerator

NODE_CLASS_MAPPINGS = {
    "DPRandomGenerator": DPRandomGenerator,
    "DPCombinatorialGenerator": DPCombinatorialGenerator,
    "DPFeelingLucky": DPFeelingLucky,
    "DPJinja": DPJinja,
    "DPOutput": OutputString,
}

# A dictionary that contains the friendly/humanly readable titles for the nodes
NODE_DISPLAY_NAME_MAPPINGS = {
    "DPRandomGenerator": "Random Prompts",
    "DPCombinatorialGenerator": "Combinatorial Prompts",
    "DPFeelingLucky": "I'm Feeling Lucky",
    "DPJinja": "Jinja2 Templates",
    "DPOutput": "OutputString",
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
```
