### ISSUE TITLE
Cannot import ComfyUI_node_Lilly module for custom nodes: 'gbk' codec can't encode character '\u2771'

### ISSUE THREAD

**Issue by whmc76** [adieyal/comfyui-dynamicprompts#5]
this is the log when i start up comfyui. could you help fix this? i'm really need a wildcard node for many workflow.many thx.

E:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-08-08 13:44:04.500512

Prestartup times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 32525 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints E:/sd-webui-aki-v4.2/models/Stable-diffusion
Adding extra search path configs E:/sd-webui-aki-v4.2/models/Stable-diffusion
Adding extra search path vae E:/sd-webui-aki-v4.2/models/VAE
Adding extra search path loras E:/sd-webui-aki-v4.2/models/Lora
Adding extra search path loras E:/sd-webui-aki-v4.2/models/LyCORIS
Adding extra search path upscale_models E:/sd-webui-aki-v4.2/models/ESRGAN
Adding extra search path upscale_models E:/sd-webui-aki-v4.2/models/RealESRGAN
Adding extra search path upscale_models E:/sd-webui-aki-v4.2/models/SwinIR
Adding extra search path embeddings E:/sd-webui-aki-v4.2/embeddings
Adding extra search path hypernetworks E:/sd-webui-aki-v4.2/models/hypernetworks
Adding extra search path controlnet E:/sd-webui-aki-v4.2/models/ControlNet
### ComfyUI Revision: 1265 [1f0f4cc0]
Comfyroll Custom Nodes: Loaded
__name__ : ComfyUI_node_Lilly
__file__ : E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  E:\ComfyUI_windows_portable
─────────────────────────────────────────────────────  init start  ─────────────────────────────────────────────────────__name__ : custom_nodes.ComfyUI_node_Lilly
__file__ : E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py
os.path.basename(__file__) : __init__.py
os.path.splitext(os.path.basename(__file__))[0] : __init__
working directory :  E:\ComfyUI_windows_portable
[13:44:13] Load ok   : CheckpointLoaderRandom                                                             __init__.py:83[13:44:13] os.path.basename(__file__) :  mypath.py                                                          mypath.py:29           os.path.abspath(__file__)  :                                                                     mypath.py:32           E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\mypath.py
           os.path.abspath(__file__)  :                                                                     mypath.py:35           E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\mypath.py
           os.path.normpath(__file__) :                                                                     mypath.py:38           E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\mypath.py
           os.path.dirname(normpath) : E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly  mypath.py:41           os.path.basename(normpath) : mypath.py                                                           mypath.py:44           os.path.abspath(sys.modules['__main__'].__file__) : E:\ComfyUI_windows_portable\ComfyUI\main.py  mypath.py:47           os.path.dirname(mainFile) : E:\ComfyUI_windows_portable\ComfyUI                                  mypath.py:49           Load ok   : CheckpointLoaderSimpleText                                                         __init__.py:83           wildcards card_path :                                                                         wildcards.py:36           E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\..\..\wildcards\**\*.txt
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py", line 74, in add
    exec(f"import {md}{name}")
  File "<string>", line 1, in <module>
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\CLIPTextEncodeWildcards.py", line 10, in <module>
    from .wildcards import wildcards
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\wildcards.py", line 218, in <module>
    print("wildcards test : "+wildcards.run("__aest__"))
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\wildcards.py", line 197, in run
    wildcards.card_load()
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\wildcards.py", line 177, in card_load
    lines = f.readlines()
  File "encodings\cp1254.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 55: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py", line 91, in <module>
    add("CLIPTextEncodeWildcards",["CLIPTextEncodeWildcards","CLIPTextEncodeWildcards2","CLIPTextEncodeWildcards3"])
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly\__init__.py", line 85, in add
    console.print_exception()
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\rich\console.py", line 1870, in print_exception
    self.print(traceback)
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\rich\console.py", line 1672, in print
    with self:
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\rich\console.py", line 864, in __exit__
    self._exit_buffer()
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\rich\console.py", line 822, in _exit_buffer
    self._check_buffer()
  File "E:\ComfyUI_windows_portable\python_embeded\lib\site-packages\rich\console.py", line 2039, in _check_buffer
    write(text)
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 22, in write
    self.file.write(message)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2771' in position 614: illegal multibyte sequence
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_node_Lilly module for custom nodes: 'gbk' codec can't encode character '\u2771' in position 614: illegal multibyte sequence
*** You may need to add PYTHONIOENCODING=utf-8 to your environment ***
Total VRAM 24564 MB, total RAM 32525 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync

**Comment by whmc76** [comment]
sorry it's other node's issue hh
